### ISSUE TITLE
operators not slow anymore?

### ISSUE THREAD

**Issue by niner** [raku-community-modules/Color#5]
nine@sphinx:~> time perl6 -e 'use Color;'
real    0m0.246s

nine@sphinx:~> time perl6 -e 'use Color; use Color::Operators;'
real    0m0.304s

Looks like importing those operators is not as slow anymore (just 0.06 seconds). Maybe you could merge them back into Color?

**Comment by lizmat** [comment]
Addressed with https://github.com/raku-community-modules/Color/commit/03815bd73c
